### ISSUE TITLE
Must add trailing slace ('/') at the end of the URL

### ISSUE THREAD

**Issue by simnalamburt** [wookayin/tensorflow-talk-debugging#3]
This hyperlink:

![image](https://cloud.githubusercontent.com/assets/4435445/21580139/379fd672-d022-11e6-814f-dc0dedcb9449.png)

Does not contains trailing slash character (`/`) which leads users to 404 Page Not Found.

**Comment by wookayin** [comment]
Sorry, it was a case-sensitivity problem, I changed `TensorFlow` to `Tensorflow` and the issue was resolved. (Once I had changed repository name to ..TensorFlow.., which broke the link) Thanks for letting me know!
